### ISSUE TITLE
Alpaca Data Streaming Client is Unauthorized. Connection Limit Exceeded

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#306] opened 2021-03-22 14:45 UTC
I have been getting this really strange error/issue on multiple paper accounts where Alpaca Streaming Client connects and authenticates just fine but the Alpaca Data Streaming Client doesn't connect and authenticate properly and gives me the connection limit exceeded error then proceeds to be stuck in an endless loop of errors because of the previous issue I reported with the reconnection. This is an account that was reset twice with brand new API info btw.

Here is my console printout:

Waiting for market to open...
Market opened.
Alpaca streaming client socket opened.
Alpaca streaming client connection status is Authorized.
Alpaca data streaming client socket opened.
Alpaca data streaming client connection status is Unauthorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
connection limit exceeded

**Comment by OlegRa** [comment] 2021-03-23 13:36
@ooples The `connection limit exceeded` error is expected - you unable to use 2 or more web socket connections to the Alpaca Data API v2 streaming endpoint. The unique key for connection check is an API ID / secret key pair so just use different pairs for different connections or proxy requests through some WS multiplexer/demultiplexer.

I will close this issue because the real root cause of the long reconnection loop is not in a connection limit but in SDK reconnection logic and this problem already reported in issue #297.

**Closed by OlegRa** 2021-03-23 13:36 UTC
Labels: bug

**Comment by ooples** [comment] 2021-03-23 14:43
No I don't think you understand me. I'm able to connect just fine with some accounts and no I'm not using the same API info for any of the accounts that give this error. I can send you a private email if you want with API key info that works and some that don't work

**Comment by ooples** [comment] 2021-03-23 15:16
It is an api issue because on the accounts that give this error message I
attempt a manual disconnect then connect and authorize and it still
happens. I only noticed these errors btw once everything switched over to
the new data streaming so I'm pretty sure there is a correlation there. I
can't buy or sell stocks on the accounts that get these error messages so
this is an urgent issue for me

**Comment by OlegRa** [comment] 2021-03-23 15:25
And what SDK can do with it? If the server denies your authentication attempts and not even allow you to trade using these credentials (API ID/key pair) - what we can do from the client-side? I really want to help you but it's not possible to resolve this problem from the SDK side. I'm pretty sure that you will experience the same issues if you try to use Python or Go SDK for these problem accounts. Maybe API v2 is not enabled for them, maybe they are disabled for some reason by the server - I don't know.

I suggest you escalate this problem to the Alpaca support team. I can help you only with this SDK but not with server issues.
