### ISSUE TITLE
[BUG]: System.Net.WebSockets.WebSocketException: No such host is known. (stream.data.alpaca.markets:443)

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#499] opened 2022-04-19 21:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```cs
Alpaca data streaming client error: Unable to connect to the remote server
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
Unable to connect to the remote server

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)
   at Alpaca.Markets.StreamingClientBase`1.ConnectAndAuthenticateAsync(CancellationToken cancellationToken)
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosedImpl()
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosed()

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

No such host is known. (stream.data.alpaca.markets:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

No such host is known.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

### Expected Behavior

Started getting these connection issues today or I just didn't notice them before since I upgraded from the previous version but these are fairly constant for me and not sure why they happen. I have the reconnect parameters set 

### Steps To Reproduce

Started getting this issue today

### Environment

I'm using the latest prerelease

**Comment by OlegRa** [comment] 2022-04-20 07:42
0. I need the exact version of SDK for investigation and it would be helpful for other users to know the exact version if they will have the similar problems in future
1. What is your OS version/bitness and .NET runtime version/bitness? I've made one small change that can affect .NET 5 (and later) apps running on Linux but this change relates to HTTP connection, not WS one.
2. Are you able to connect using the previous version of SDK?

**Comment by OlegRa** [comment] 2022-04-21 13:48
I'm still not able to reproduce this issue on my side. But I have an idea that can be a root cause and the last 6.0.3-beta5 version of the SDK package contains a fix for this case. Please, @ooples, test this version and tell me about the results.

**Comment by ooples** [comment] 2022-04-21 13:50
Ok I won't be able to start testing until tomorrow but I will let you know

**Comment by ooples** [comment] 2022-05-02 15:56
@OlegRa It looks like this issue was fixed from what I'm seeing but it seems to introduce a different error altogether. This is the message I see when it has connection errors related to the above issues:

Alpaca data streaming client error: Writing is not allowed after writer was completed.
Exception Type:
System.InvalidOperationException

Exception Message:
Writing is not allowed after writer was completed.

Exception StackTrace:
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.SendAsync(String message, CancellationToken cancellationToken)
   at Alpaca.Markets.DataStreamingClientBase`1.sendSubscriptionRequestsAsync(JsonAction action, IEnumerable`1 streams, CancellationToken cancellationToken)
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosedImpl()
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosed()

Exception Target Site:
ThrowInvalidOperationException_NoWritingAllowed

Exception Source:
System.IO.Pipelines

**Comment by ooples** [comment] 2022-05-02 16:56
@OlegRa Actually looks like it did prevent as many occurences of the original issue but the issue is still happening and this is a small snippet of what I'm seeing quite a bit of on my end:

Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
Unable to connect to the remote server

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

No such host is known. (stream.data.alpaca.markets:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

No such host is known.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

Alpaca data streaming client error: Writing is not allowed after writer was completed.
Exception Type:
System.InvalidOperationException

Exception Message:
Writing is not allowed after writer was completed.

Exception StackTrace:
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.SendAsync(String message, CancellationToken cancellationToken)
   at Alpaca.Markets.DataStreamingClientBase`1.sendSubscriptionRequestsAsync(JsonAction action, IEnumerable`1 streams, CancellationToken cancellationToken)
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosedImpl()
   at Alpaca.Markets.Extensions.ClientWithReconnectBase`1.handleSocketClosed()

Exception Target Site:
ThrowInvalidOperationException_NoWritingAllowed

Exception Source:
System.IO.Pipelines

Alpaca streaming client error: Unable to connect to the remote server
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
Unable to connect to the remote server

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

No such host is known. (paper-api.alpaca.markets:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

No such host is known.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

Exception Type:
System.Net.Sockets.SocketException

Exception Message:
No such host is known.

Exception StackTrace:
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at Polly.Utilities.ExceptionExtensions.RethrowWithOriginalStackTraceIfDiffersFrom(Exception exceptionPossiblyToThrow, Exception exceptionToCompare)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.GetTopLevelInfo() in E:\OoplesFinanceAdminClient\OoplesFinanceAdminClient\AlpacaApi.cs:line 2063

Exception Target Site:
ThrowException

Exception Source:
System.Net.Sockets

**Comment by OlegRa** [comment] 2022-05-02 19:45
According to this long stack reconnection logic works as expected (in general). The `Writing is not allowed after writer was completed` error generated only after several reconnect attempts and I'll check is it a real bug or if we can just suppress this error. The original problem (host not found) is related to DNS resolving and SDK is unable to do anything with it - if after several reconnections attempt DNS name is still not mapped to the IP address we can only report this error.

If you run your code in the container check that name resolution works properly and your DNS server is available from the container's network. I've never seen such a problem on my local PC and GitHub-based integration tests also never fail with this error message.

**Comment by ooples** [comment] 2022-05-03 14:16
@OlegRa I do get your logic on this issue but this version compared to the previous version is wildly different on my end. As an example the previous version had a total of one related error and these newer versions have over 65 related errors which logically doesn't make sense since this problem only started two versions ago.

**Comment by OlegRa** [comment] 2022-05-03 19:48
In previous versions, any error on the initial connection attempt throws an exception. But at the same time, any other error is reported via the `OnError` event. As a result reconnection logic failed on the first attempt and the exception contains information only about a single event.

In updated versions, all exceptions are reported using the `OnError` event and as a result, reconnection works as expected. The pipe writing error is a result of a minor bug - even if all reconnect attempts are failed we try to re-subscribe. I've already fixed this bug and most probably will publish an updated extensions package later today.

**Closed** 2022-05-11 09:16 UTC
Labels: bug
