### ISSUE TITLE
Sockets keep closing randomly

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#239] opened 2020-10-06 14:57 UTC
This has been a long standing issue I have had with this api but it seems to have been worse for me lately. I can't run the api for more than 5 minutes without the socket randomly closing on me with no errors or messages of any kind letting me know why it is happening. I have sent you the code I'm using so you can verify on your end.

**Comment by OlegRa** [comment] 2020-10-07 16:04
@ooples Yesterday I was able to reproduce this issue but today all work fine for a long time.

Maybe my initial approach for delegating re-connection to SDK clients was wrong and it's better to handle such events automatically in SDK itself. Unfortunately, it's not a safe change and potentially can unstable current version. I'll add explicit ping sending parameters into the web socket handling objects as an initial fix.

In the next major version (4.0) I'll add reconnection logic into the base streaming client.

**Comment by ooples** [comment] 2020-10-07 16:13
When do you anticipate the release of version 4.0?

**Comment by OlegRa** [comment] 2020-10-07 16:16
@ooples ETA for the 4.0 final release is the end of this year. But I'll start working on this version as soon as I publish the final stable release of the 3.9.0 version.

**Comment by OlegRa** [comment] 2020-10-10 10:21
@ooples I've found another option for adding reconnection without changing existing code so this change is backward-compatible, fully optional, and can be easily tested by you. You have to add another package named `Alpaca.Markets.Extensions` (latest preview version 3.9.0-rc2) into your project and call the `WithReconnect` extension method on a newly created instance of the `IAlpacaDataStreamingClient` or `IPolygonStreamingClient` interface. This method will wrap the passed argument into a helper class that implements re-connection and re-subscription logic. You can also specify reconnection parameters (max reconnection attempts and min/max delay between reconnection attempts) using the second optional argument of this method.

**Comment by ooples** [comment] 2020-10-10 14:59
I won't be able to test it until Monday but I had a couple of questions/observations. Can you merge the two extensions classes together for both clients? It would definitely help clean up the code with the ambiguous calls for sure. Also what are the default values for the reconnection parameters?

**Comment by OlegRa** [comment] 2020-10-11 17:11
The default values for the reconnection logic are 5 attempts with 1 to 5 seconds random delay between attempts.
I'm unable to merge both implementations into the single one because `IAlpacaDataStreamingClient` and `IPolygonStreamingClient` interfaces are different and I have to implement different wrappers. But after implementing issue #137 (now planned for the 4.0 release scope) it would be possible I hope.

**Comment by ooples** [comment] 2020-10-11 18:20
Thank you for that info. I'm actually talking about the AlpacaDataStreamingClient in particular since that is the only one I have tried so far. You have the AlpacaDataStreamingClientExtension class existing in both the Alpaca.Markets and the Alpaca.Markets.Extensions when I feel like that should only exist in the Alpaca.Markets.Extensions for obvious reasons. Hope you understand what I'm trying to say. I'm definitely looking forward to the 4.0 release

**Comment by OlegRa** [comment] 2020-10-11 18:42
OK, maybe you're right it's not a problem to more old one (related to subscriptions) into the extensions library because it exists only in pre-release versions and it's OK to break compatibility in this case. I'll check and if it is possible (no other dependencies) I'll do it in version 3.9.0-rc3 and I hope it would be the last big change before the final version of 3.9 and switching to the big 4.0 release.

**Comment by willsheydo** [comment] 2020-10-16 01:28
Thanks @OlegRa ,

Can you please add the Auto-reconnection logic for all the websocket connections?
I'm having disconnecting issues with the AlpacaStreamingClient too.

Thanks in advance!

**Comment by jeffwlandry** [comment] 2020-10-20 14:54
Over the last two weeks, my experience is that the polygon.io streaming socket closes without meaningful reason more and more often.  Yesterday (Oct 19,2020) this occurred 3 times between 1330 and 1550 (US Eastern).  Friday (Oct 16) this occurred 6 times between 1037 and 1243.  Probably more often for the whole day, but I have gaps in my run time as I work on the program.


Fortunately, I have been able to implement reasonable recovery.  However, my interest is why is this occurring?  Is there a flaw in this c# api, or is there a problem on the polygon side?  Recovery logic is well and good, but not a substitute for reliable, steady connections.

Or is this a function of my infrastructure?  I have 18 jumps between my machine and api.polygon.io.  Tracert says 24ms.  I can't ping api.polygon.io so I don't know what the typical latency is.

I have 13 jumps between my machine and paper-api.alpaca.markets with a typical ping of 21ms.  I had a friend out side of Ashburn, VA ping paper-api.  He has two jumps and a 10ms average.

The connection problem has been getting worse over the last few months.  Internet traffic has been growing over the last few months.  Any chance there is a connection?

What is the possibility of Alpaca providing a VPN capability with optimized routing which is somehow automagically used when connecting to the api? Or is there a cloud provider with VMs with lower latency to the api sites?

Thank you,
jeff landry

**Comment by OlegRa** [comment] 2020-10-21 22:44
@jerwheaton You are right - stability of the WebSocket connection (and any long-running TCP connection) heavily depends on the network conditions of your internet connection. I'm not sure that a VPN connection will solve ALL the problems - in any case, it will not change routing from your PC to Alpaca. But the idea with cloud looks much better for me - if you will connect to Alpaca API from the same data center or at least from the same provider network you should experience fewer disconnects (in theory). So try to run your code in the Google Cloud (looks like Alpaca uses this cloud platform for their API hosting)

**Comment by jeffwlandry** [comment] 2020-10-22 15:19
Thank you, I’ll look into that.  It’s polygon that I have the most connection trouble with.  Do you know if they are hosted by a particular provider?

Jeff

**Comment by OlegRa** [comment] 2020-10-26 11:15
@jeffwlandry I'm not sure but according to IP/DNS trace/lookup info, they use their own data center in the US.

**Comment by OlegRa** [comment] 2020-10-26 11:32
I would close it right now in the scope of 3.9.0 release preparation. The separate issue related to this logic #248 will be fixed in the final 3.9.0 release.

**Closed by OlegRa** 2020-10-26 11:32 UTC
Labels: bug
