### ISSUE TITLE
JsonSerializationException: Required property 'db_latency'

### ISSUE THREAD

**Issue by ghost** [alpacahq/alpaca-trade-api-csharp#166] opened 2020-01-22 20:23 UTC
When calling `PolygonDataClient.ListMinuteAggregatesAsync` I get following error.

`Newtonsoft.Json.JsonSerializationException: Required property 'db_latency' not found in JSON.`

This appears to be a required property of JsonHistoricalItems, which I believe is used to try to parse the JSON response from the Plygon Aggregates endpoint, which, returns no "db_latency" property in its JSON response.

I'm using the latest beta version, should be easy enough to reproduce as it happens every time, but, I was running it against MSFT with a multiplier of 1, for a single day date range (midnight to midnight, Eastern Time).

**Comment by scyentyfyc** [comment] 2020-01-22 20:53
Sorry, I used the wrong account to post this question, so I ghosted that account.  I'm the one that posted this.

**Comment by OlegRa** [comment] 2020-01-22 22:48
@scyentyfyc Try to use the 3rd beta of 3.5.0 version available on NuGet. If the problem is resolved, please, close this issue.

**Comment by scyentyfyc** [comment] 2020-01-23 00:58
Perfect.  Thanks so much for the quick turnaround!

**Closed** 2020-01-25 20:03 UTC
Labels: bug
