### ISSUE TITLE
3.6 beta compiler error

### ISSUE THREAD

**Issue by kwcoffee1** [alpacahq/alpaca-trade-api-csharp#189] opened 2020-03-23 01:30 UTC
When I compiling Alpaca.Market out-of-box, I get the following two errors:

For Helpers:ActionExtensions.cs Error CS8604
Possible null reference argument for parameter 'obj' in 'void Action<TApi>.Invoke(TApi obj)'.	Alpaca.Markets (net45), Alpaca.Markets (netstandard1.3), Alpaca.Markets (netstandard2.0), Alpaca.Markets (netstandard2.1) ...\Alpaca.Markets\Helpers\ActionExtensions.cs 13 Active

AND ERRROR

For Helpers:HttpClientExtensions.cs Error CS8604 Suppression State
Error CS8603 Possible null reference return. Alpaca.Markets (net45), Alpaca.Markets (netstandard1.3), Alpaca.Markets (netstandard2.0), Alpaca.Markets (netstandard2.1)
...\Alpaca.Markets\Helpers\HttpClientExtensions.cs 68 Active

**Comment by OlegRa** [comment] 2020-03-23 07:24
@kwcoffee1 Unfortunately, I'm unable to reproduce this problem on my side using the latest VS 2019 and .NET Framework / .NET Core SDKs. And I don't see such a problem in GitHub CI/CD logs.

Could you please provide more information about your environment? What are your OS/VS/.NET SDK versions? If you'll provide full build output it also will be very helpful for investigating this issue.

**Comment by OlegRa** [comment] 2020-03-23 07:54
@kwcoffee1 Reproduced on my side after installing all the latest VS updates. Still not reproduced on the GitHub CI/CD. I'll check it ASAP.

**Comment by OlegRa** [comment] 2020-03-23 08:30
Fixed in the `development` branch. GitHub CI/CD scripts updated.

@kwcoffee1 Please, test on your side and close if the problem is solved.

**Closed** 2020-04-06 17:15 UTC
Labels: bug
