### ISSUE TITLE
[BUG]: Cannot access a disposed object. Object name: 'SslStream'

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#514] opened 2022-05-17 19:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting two new issues using the latest prerelease version and they are somewhat related so I'm going to put them both on here. They both seem to occur right after the other 

```
First: Cannot access a disposed object.
Object name: 'SslStream'.

   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|138_0(ExceptionDispatchInfo e)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.FlushAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
```

```
Exception Type:
System.TimeoutException

Exception Message:
HTTP response timed out.

Exception StackTrace:
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.sendAsyncWithTimeout(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass2_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.GetTopLevelInfo() in E:\OoplesFinanceAdminClient\OoplesFinanceAdminClient\AlpacaApi.cs:line 2063

Exception Target Site:
MoveNext

Exception Source:
Alpaca.Markets

A task was canceled.

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.sendAsyncWithTimeout(HttpRequestMessage request, CancellationToken cancellationToken)
```

### Environment

```markdown
- SDK Version: 6.03 rc2
- OS (version, bitness): Windows 10 
- .NET SDK (version): .net 6
- target process .NET version/bitness: 64 bit
```

**Comment by ooples** [comment] 2022-05-17 19:31
@OlegRa I also saw a few messages about http request going beyond the 100 second http timeout or something along those lines but couldn't find the full stack trace info. Any plans on allowing the users to override that 100 second timeout btw?

**Comment by OlegRa** [comment] 2022-05-19 10:38
I've checked the .NET source code and can confirm that the root cause of both issues is timeout processing inside the .NET HttpClient implementation. What exactly do you request in your `GetTopLevelInfo` method? The 100 seconds default timeout looks good for the most REST endpoints except the single one that is used for closing all positions. The `DeleteAllPositionsRequest` provides a way for specifying the request-specific timeout.

I don't think that providing a timeout for each request is a good idea. Maybe a global way for overriding timeout using the ThrottleParameters would be good enough for most use cases. What do you think, @ooples about this approach? I like it because it's backward compatible and will not affect all users.

**Comment by ooples** [comment] 2022-05-19 13:37
I really like the idea of overriding the timeout through the throttle
parameters

**Comment by ooples** [comment] 2022-05-20 14:43
@OlegRa Also as a side note, I looked through the user wiki and tutorials and didn't see an example for newer users to utilize the throttle parameters so just thought it would be useful to add an example

**Comment by ooples** [comment] 2022-05-30 16:13
@OlegRa I'm testing out these new changes but I have some initial thoughts for the timeout property. First it seems that it is the only property that doesn't have an initialization parameter in the ThrottleParameters class so I do think you should add it. Second the property name is exactly the same as the default System.Threading.Timeout which in my opinion will cause problems for users so I think it should be changed to maxTimeout or maxTimeOut

**Comment by OlegRa** [comment] 2022-05-30 17:39
@ooples There are some reasons behind this design decision:

- This new property is optional and I don't want to make another constructor with this optional property (default argument values are binary-incompatible so it's not an option). Moreover, the concrete timeout value is captured for each request so theoretically you can change the timeout value before each call instead of all other properties of the `ThrottleParameters` objects (all of them are read-only).
- I'm not sure about possible problems with name resolution - if you have any example where the compiler is unable to correctly select between the property name and type name, please, share it. And again, I just want to be closer to the original `HttpClient` design - this type also contains the `Timeout` [property](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-6.0) and I've never had any serious issues with name resolutions related to this property.

**Comment by ooples** [comment] 2022-05-31 13:08
@OlegRa I'm testing the brand new changes but there is a serious issue I'm noticing. I simulated internet going down by restarting my ethernet adapter but with this latest version, the sockets get closed after erroring out which is expected but there seems to be no attempts at reopening the connection. I haven't changed my reconnection logic at all and only related change was to override the new timeout setting

**Comment by ooples** [comment] 2022-05-31 14:51
@OlegRa I'm able to replicate this by disabling the ethernet adapter and then enabling it again. Socket stays closed and doesn't attempt to reconnect. However when running the same code without messing with the ethernet adapter, I can see that it does attempt to reconnect on its own.

**Comment by OlegRa** [comment] 2022-05-31 15:58
> @OlegRa I'm able to replicate this by disabling the ethernet adapter and then enabling it again. Socket stays closed and doesn't attempt to reconnect. However when running the same code without messing with the ethernet adapter, I can see that it does attempt to reconnect on its own.

@ooples How does socket reconnection logic (most probably your mean one of the streaming clients) relate to the HTTP timeout? If you have a problem related to streaming client's reconnection in the latest SDK release, please, report it as a separate issue.

**Closed** 2022-05-31 16:03 UTC
Labels: bug, question
