### ISSUE TITLE
Not receiving after hours data via subscription updates

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#282] opened 2021-02-17 21:50 UTC
I didn't change anything in my code other than update to the latest version which I believe is alpha 5 and I'm suddenly not receiving any updates during the market after hours. I'm using the AlpacaDataStreamingClient so was there a drastic change for the latest version or am I just missing something?

EDIT: I'm not receiving any price updates at all during market hours or after market hours

**Comment by OlegRa** [comment] 2021-02-19 21:53
@ooples You are right - this was a major regression as a result of the significant refactoring. It should work as expected in the new [5.0.0-alpha5](../releases/tag/sdk-5.0.0-alpha5) release (also available on the NuGet).

**Comment by jeffwlandry** [comment] 2021-02-22 15:12
Friday my program worked with alpha 1.  Starting Saturday I can no longer get access to polygon historic data.  Today I get 
"access key verification failed : request is unauthorized (generate APCA-API-KEY-ID and APCA-API-ACCESS-SECRET-KEY from dashboard and include in HTTP header) (Code = 40110000)"
I regenerated all my keys and still get this failure message.

**Comment by jeffwlandry** [comment] 2021-02-22 16:38
some time before 11:57 US Eastern time my app started authenticating and getting paper polygon  real time data.  

The historic data is still a problem.  It appears the polygon authentication now works, but throws "not found" exception on the last line of the following line of code:
            bool done = false;  //continue while loop
            fakeStreamTrade trade = null;
            IReadOnlyList<IHistoricalTrade> brokerTrades;
            List<fakeStreamTrade> result = new List<fakeStreamTrade>(300000);   //arbitrary preallocation for performance enhancement
            fakeStreamTrade lastPoint = null;
            try
            {
                onDisplayBusyMessage(new displayMessageEventArgs($"Getting {symbol} historic data from {start} to {end}", Microsoft.Extensions.Logging.LogLevel.Information));
                HistoricalRequest request = new HistoricalRequest(symbol, start);
                request.Timestamp = new DateTimeOffset(start.ToUniversalTime()).ToUnixTimeMilliseconds() * 1000000;  //millisec is 1,000,000 nanoseconds 
                request.TimestampLimit = new DateTimeOffset(end.ToUniversalTime()).ToUnixTimeMilliseconds() * 1000000;
                request.Reverse = false;
                //get first batch of trades
                brokerTrades = (await polygonDataClient.ListHistoricalTradesAsync(request)).Items;

Is the 2/26 historic code deadline already in place?

Thank you,
jeff

**Comment by ooples** [comment] 2021-02-22 16:39
I can confirm that the issue is fixed in the latest version

**Comment by jeffwlandry** [comment] 2021-02-22 16:54
Thank you for that information, let me withdraw the previous post, after your post closer examination revealed I was requesting data for a non-trading date (rats, one more thing I have to look into).

Thank you for that information.  By latest version do you mean alpha 5?  When I go past alpha 3 I get errors for all the polygon data methods:'PolygonStreamingClient' does not contain a definition for 'TradeReceived' and no accessible extension method 'TradeReceived' accepting a first argument of type 'PolygonStreamingClient' could be found (are you missing a using directive or an assembly reference?)	stockCommon_Alpaca	C:\Users\jeffl\source\repos\moneyFromTrees\alpaca\stockCommon_Alpaca\broker_alpaca.cs	85	Active

I now only see socketOpened and Closed events for the streaming client.  These work in alpha 3.  If you don't concur, I need to open a different issue.

thank you,
jeff

**Comment by ooples** [comment] 2021-02-22 17:02
Yes alpha 5 fixes all of this and you can now do this in alpha 5 using the polygon streaming client:

var priceSubscription = polygonStreamingClient.GetMinuteAggSubscription();
                    priceSubscription.Received += (agg) =>
                    {
                        // handle your processing of the streaming data here
                    };
                    polygonStreamingClient.Subscribe(priceSubscription);

**Comment by OlegRa** [comment] 2021-02-22 17:15
@jeffwlandry If you need a stable and well-documented version of SDK - use version 4.0, not 5.0 because the last one is mostly experimental, doesn't provide backward compatibility with old code and online examples, and can be just broken for a while. 

Shortly speaking - use it only for experiments on the paper environment and never use it for production trading. The 4.0 is LTS and will be supported for months. I'm unable to provide the exact date of end-of-support for this version but it will be definitely not this year.

I have plans to stabilize the public surface of version 5.0 in the upcoming month and spend next quarter on beta-testing for stability and code quality.

**Comment by OlegRa** [comment] 2021-02-22 17:16
@ooples Please, test it this week, and if you'll not find any problem close this issue this Friday :)

**Comment by jeffwlandry** [comment] 2021-02-22 17:22
Oleg:

I owe you a major apology.   Clearly I don’t understand how the GitHub and wiki sites function.  Following oooples note, I searched around further and found the directions on the current subscription technique.  Changes a bit of my code and execution, but I should have been more on top of things.

I do realize alpha technically means pre-production.  But losing money is losing money so I enjoy myself by moving up to .net 6 and using the alphas.

I got caught here by assuming the notice of alpaca no longer providing polygon data meant you had the inside scoop and were moving alpha to the new stuff and abandoning the old stuff.

Entirely my fault and I should have looked for the latest documentation and asked instead of making completely unfounded assumptions.

Thanks,
jeff

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jeffwlandry** [comment] 2021-02-22 17:25
@ooples  did i just reopen this after you closed it?  Sorry, but going to let you close it again.

jeff

**Comment by ooples** [comment] 2021-02-22 17:26
I reopened it because I accidentally hit the close button but I will close it after I can do more extensive testing this week

**Closed** 2021-02-26 22:09 UTC
Labels: bug

**Comment by jeffwlandry** [comment] 2021-03-05 21:39
historic trade timeutc seems to be US East Coast time marked as utc.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
