### ISSUE TITLE
PolygonDataClient Error 401 - Unauthorized

### ISSUE THREAD

**Issue by jzderadicka** [alpacahq/alpaca-trade-api-csharp#218] opened 2020-06-23 03:13 UTC
Receive error unauthorized when using PolygonDataClient.

	[TestClass]
	public class Alpaca_Markets_PolygonDataClient
	{
		private const string id = "MY_LIVE_ID";
		private readonly PolygonDataClient polygonDataClient = Environments.Live.GetPolygonDataClient(id);

		[TestMethod]
		public async Task ListAggregatesAsync()
		{
			IHistoricalItems<IAgg> history = null;

			try
			{
				var aggregatesRequest = new AggregatesRequest("SPY", new AggregationPeriod(1, AggregationPeriodUnit.Day));
				TimeInterval.SetInclusiveTimeInterval(aggregatesRequest, DateTime.UtcNow - TimeSpan.FromDays(1), DateTime.UtcNow);
				history = (await polygonDataClient.ListAggregatesAsync(aggregatesRequest));
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
			}

			Assert.IsTrue(history != null);
			Assert.IsTrue(history.QueryCount == 1);
		}
	}

Standard Output result is: Unauthorized

**Comment by OlegRa** [comment] 2020-06-23 08:00
@jzderadicka I've reproduced this problem on my side but the same code works fine if I provide normal Polygon.io API key (generated by Polygon). Looks like the root cause of this problem is on the server-side (authentication issue between Alpaca and Polygon).

**Comment by OlegRa** [comment] 2020-06-25 14:10
@umitanuki I'll close it in this case. @jzderadicka If you

**Closed by OlegRa** 2020-06-25 14:10 UTC
Labels: bug
