### ISSUE TITLE
OnTradeUpdate not stable

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#170] opened 2020-02-06 20:32 UTC
I'm posting this here only because I'm using the C# API.  I'm not sure if my issues are with the ALPACA backend or with the AlpacaStreamingClient.

I've been having many instances where I place on order....PostOrderAsync returns an accepted order, the order shows up in the ALPACA web interface(so it's active), but nothing gets returned ever through OnTradeUpdate.  I have no way to debug this..so this is just an FYI for you.  There also is no pattern to it.  If I re-initialize the object, it's fine for awhile, then it stops and once it stops working it's dead.  Some days it works fine all day and then others it just bombs.  Should I open/close the streaming connection after every PostOrderAsync?

But as a result I need to strip out all use of AlpacaStreamingClient for now and move to ListOrdersAsync or GetOrderAsync..to verify the status of an active order. 

Using 3.5.0.0

**Comment by zhaizhe111** [comment] 2020-02-07 05:42
I have the same issue

**Comment by OlegRa** [comment] 2020-02-07 18:56
@pratttrader @zhaizhe111 - I've tried to reproduce this problem on my side but (as expected) without any success. Could you please provide me more information about this problem?

1. What is your target application is - is it a console app, Windows application, or web app (back-end)?
2. Which version of .NET do you use for your application? I need the exact version of the used runtime and the exact version of SDK.
3. Is it 32- or 64-bit application? I don't ask about OS bitness - it's about application bitness.
4. What is your target OS - Windows, Linux, or maybe MacOS? Again, I need an exact version of your OS for creating a test environment.
5. Have you subscribed on `SocketClosed` and `OnError` events of `AlpacaStreamingClient` class? If not, subscribe first one and do reconnect in case of the first one. SDK does not provide reconnect logic for streaming clients (but now I'm thinking about this optional feature).

**Comment by pratttrader** [comment] 2020-02-07 19:14
This is a Windows app, .NET 4.5 x86  running on Windows 64 bit.
I have not attached to those events...I was thinking about that though.  I will try that.  
Earlier today, for about an hour, I couldn't even enter an order through PostOrderAsync...it would return nothing...it must have been on their end, because it started working again.  I posted a comment on their forum.
I'll wire up a handler for SocketClosed today and try it next week.

**Comment by OlegRa** [comment] 2020-02-07 19:17
@pratttrader Of course, the main question is - that Alpaca environment do you use? Paper-only environment updated much often and as a result, you can experience 'strange' API behavior often.

**Comment by pratttrader** [comment] 2020-02-07 19:24
yes, this is paper only..

**Comment by pratttrader** [comment] 2020-02-07 22:51
So should the DisconnectAsync() method raise the SocketClosed Event?  To test my change, what should I use to "close" the socket?  The only thing I see is DisconnectAsync, and that's not raising the SocketClosed Event.

**Comment by OlegRa** [comment] 2020-02-08 15:07
The `DisconnectAsync` call will not trigger the `SocketClosed` event - this event will be triggered by the underlying web socket component only in case of 'unexpected' disconnections. For example, if a web socket connection will be interrupted by a server or as a result of generic network failure. If you close connection from the client you know that it's closed and there is no reason to report it via this event.

**Comment by pratttrader** [comment] 2020-02-09 19:18
I'm trying to add my own auto-reconnect function in my application, using what is available to me from Alpaca.Markets.  A streaming connection is useless if doesn't at least try to self-correct when the socket is broken for whatever reason.  The idea I have is like other brokers do it where it tries to reconnect, say 10x, every 4 seconds and then just stop...assuming that the socket/network connection is just dead. 

The problem I'm facing is this: if I'm connected with the AlpacaStreamingClient, and manually break the network connection...it raises the SocketClosed event.  Good.  But when I go back to ConnectAsync with the connection still broken,  it raises "The socket is connected, you needn't connect again!" exception.....but it's not actually connected.

Is that just an incorrect error message?  This is all being triggered  from the SocketClosed event.  

Thanks

**Comment by OlegRa** [comment] 2020-02-10 09:58
@pratttrader I'm sorry for your disappointments but unfortunately, the problem is not in Alpaca SDK itself and I don't know how to fix it easily right now.

We use WebSocket4Net library for all web socket communications in Alpaca SDK and according to their issue tracker, this library has a problem with re-connection logic (see details [here](https://github.com/kerryjiang/WebSocket4Net/issues/99)).

I see the next possibilities for you (from simplest to hardest from my perspective):

1. Re-create the whole `AlpacaStreamingClient` object on each connection lost. Yes, it's expensive but in this case, you will have a new fresh connection with a new underlying web socket object.
2. Try to implement your own `IWebSocketFactory` interface using the existing `WebSocket4NetFactory` class as an example. In this custom interface implementation, you can re-create only the underlying `WebSocket` object and resolve this issue.
3. Try another web socket client available in Alpaca SDK - WebSocketSharp. This client available only in .NET 4.5 builds of SDK and you need more work for enabling it but it can be an option for you.
4. Try to push WebSocket4Net maintainers and force problem fixing on their side. On my side, I can re-integrate the updated version of WebSocket4Net library into Alpaca SDK as soon as problem will be fixed.

Implementing re-connection logic inside SDK is a breaking change and I'm not ready to do it right now (need more time for designing this feature properly).

**Comment by pratttrader** [comment] 2020-02-10 16:17
Thanks for the reply.  I'm not disappointed because this is what I do.

I currently use another broker and before I move everything to ALPACA I just need to test everything from a trading perspective and a technology perspective. 

I'm not asking for an implementation of logic because in my view, that's my responsibliity.  I was pointing out that I'm getting "Socket Connected", when it's not...which is hard to use on my end.  All I have to work with are exceptions, object states and properties, and if something is inaccurate, it makes it hard.

Right now I have it set to attemptt a reconnect, and if that fails (as in, my provider's connection has dropped), it releases the ALPACA objects and alerts me.  From there, I might cycle every 10 seconds to try again.   I'm also using another broker's connection for real-time prices, so I handle their exceptions and tie that it into my ALPACA code..but I need to plan on the assumption that that wont always be there.

Additionally I'm building a seperate "Network Listener" which monitors my own network connection.

I think have a plan going forward...thanks for the help.

**Closed** 2020-02-10 16:18 UTC
Labels: bug, question
