### ISSUE TITLE
OCO order not working

### ISSUE THREAD

**Issue by nbmrao** [alpacahq/alpaca-trade-api-csharp#280] opened 2021-02-04 14:52 UTC
Hello, 
I see the following exception with the following code using the C# SDK. My goal is to set a OCO sell order with a target, stop and stop limit. Any help is greatly appreciated.

Code:

```cs
await alpacaTradingClient.PostOrderAsync(OrderSide.Sell.Limit(positionInfo.ticker, positionInfo.quantity,
target).WithDuration(TimeInForce.Day).OneCancelsOther(stop, limit));
```

Exception:

```cs
InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
at Alpaca.Markets.HttpClientExtensions.d__6.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Alpaca.Markets.HttpClientExtensions.d__42.MoveNext() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__33.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by OlegRa** [comment] 2021-02-11 18:33
@nbmrao AFAIU this issue is not easy to reproduce because it related to server-side throttling and depends on a number of client-side requests performed in the last throttling period (1 minute). I've removed any HTTP request re-sending for non-idempotent requests (all except the `GET` verb) in [4.0.3](../releases/tag/sdk-4.0.3) and I'm sure it should help. I close it right now as hard to test but if you'll be able to reproduce in version 4.0.3 (or any later version of SDK) - feel free to re-open it.

**Closed by OlegRa** 2021-02-11 18:33 UTC
Labels: bug
