### ISSUE TITLE
[QUESTION]: Problem connecting to crypto data stream

### ISSUE THREAD

**Issue by tcj2001** [alpacahq/alpaca-trade-api-csharp#480] opened 2022-03-18 15:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I am trying to connect to alpacaTradingClient, alpacaDataClient, alpacaCryptoDataClient, alpacaStreamingClient, alpacaDataStreamingClient and alpacaCryptoStreamingClient on both environment at the same time using its respective keys.

I get Crypto Streaming Client on the the Last connected Environment as UnAuthorized

What I found is if I connect to only one environment there is no issue. 

I have attached a console program to replicate the issue. I am using .Net 6.0

### Anything else?

```cs
using Alpaca.Markets;
using Alpaca.Markets.Extensions;

namespace test;

class Program
{
    static void Main(string[] args)
    {
        SecretKey secretKey1;
        SecretKey secretKey2;

        //live
        string key1 = "Replace Live key";
        string secret1 = "Replace Live secret";

        //paper
        string key2 = "Replace Paper key";
        string secret2 = "Replace Paper secret";

        //live
        secretKey1 = new(key1, secret1);
        Test test1 = new Test("Live", secretKey1);
        test1.Connect();

        //paper
        secretKey2 = new(key2, secret2);
        Test test2 = new Test("Paper", secretKey2);
        test2.Connect();

        Console.ReadLine();
    }
}
public class Test
{
    private IAlpacaTradingClient alpacaTradingClient;

    private IAlpacaDataClient alpacaDataClient;
    private IAlpacaCryptoDataClient alpacaCryptoDataClient;

    private IAlpacaStreamingClient alpacaStreamingClient;

    public IAlpacaDataStreamingClient alpacaDataStreamingClient;
    public IAlpacaCryptoStreamingClient alpacaCryptoStreamingClient;
    private string environment = "";

    public Test(string environment, SecretKey secretKey)
    {
        this.environment = environment;

        if (environment == "Paper")
        {
            alpacaTradingClient = Environments.Paper.GetAlpacaTradingClient(secretKey);
            alpacaDataClient = Environments.Paper.GetAlpacaDataClient(secretKey);
            alpacaCryptoDataClient = Environments.Paper.GetAlpacaCryptoDataClient(secretKey);

            // Connect to Alpaca's websocket and listen for updates on our orders.
            alpacaStreamingClient = Environments.Paper.GetAlpacaStreamingClient(secretKey).WithReconnect();

            // Connect to Alpaca's websocket and listen for price updates.
            alpacaDataStreamingClient = Environments.Paper.GetAlpacaDataStreamingClient(secretKey).WithReconnect();
            alpacaCryptoStreamingClient = Environments.Paper.GetAlpacaCryptoStreamingClient(secretKey).WithReconnect();
        }

        if (environment == "Live")
        {
            alpacaTradingClient = Environments.Live.GetAlpacaTradingClient(secretKey);
            alpacaDataClient = Environments.Live.GetAlpacaDataClient(secretKey);
            alpacaCryptoDataClient = Environments.Live.GetAlpacaCryptoDataClient(secretKey);

            // Connect to Alpaca's websocket and listen for updates on our orders.
            alpacaStreamingClient = Environments.Live.GetAlpacaStreamingClient(secretKey).WithReconnect();

            // Connect to Alpaca's websocket and listen for price updates.
            alpacaDataStreamingClient = Environments.Live.GetAlpacaDataStreamingClient(secretKey).WithReconnect();
            alpacaCryptoStreamingClient = Environments.Live.GetAlpacaCryptoStreamingClient(secretKey).WithReconnect();
        }

        //Streaming client event
        alpacaStreamingClient.OnTradeUpdate += AlpacaStreamingClient_OnTradeUpdate;
        alpacaStreamingClient.OnError += AlpacaStreamingClient_OnError;
        alpacaStreamingClient.OnWarning += AlpacaStreamingClient_OnWarning;

        //Data Streaming client event
        alpacaDataStreamingClient.OnError += AlpacaDataStreamingClient_OnError;
        alpacaDataStreamingClient.OnWarning += AlpacaDataStreamingClient_OnWarning;
        alpacaDataStreamingClient.Connected += AlpacaDataStreamingClient_Connected;
        alpacaDataStreamingClient.SocketOpened += AlpacaDataStreamingClient_SocketOpened;
        alpacaDataStreamingClient.SocketClosed += AlpacaDataStreamingClient_SocketClosed;

        alpacaCryptoStreamingClient.OnError += AlpacaCryptoStreamingClient_OnError;
        alpacaCryptoStreamingClient.OnWarning += AlpacaCryptoStreamingClient_OnWarning;
        alpacaCryptoStreamingClient.Connected += AlpacaCryptoStreamingClient_Connected;
        alpacaCryptoStreamingClient.SocketOpened += AlpacaCryptoStreamingClient_SocketOpened;
        alpacaCryptoStreamingClient.SocketClosed += AlpacaCryptoStreamingClient_SocketClosed;
    }

    public async void Connect()
    {
        await alpacaStreamingClient.ConnectAndAuthenticateAsync();
        await alpacaDataStreamingClient.ConnectAndAuthenticateAsync();
        await alpacaCryptoStreamingClient.ConnectAndAuthenticateAsync();
    }

    private void AlpacaCryptoStreamingClient_SocketClosed()
    {
        Console.WriteLine($"{environment}: Crypto Streaming Client Socket Closed");
    }

    private void AlpacaCryptoStreamingClient_SocketOpened()
    {
        Console.WriteLine($"{environment}: Crypto Streaming Client Socket Opened");
    }

    private void AlpacaCryptoStreamingClient_Connected(AuthStatus obj)
    {
        Console.WriteLine($"{environment}: Crypto Streaming Client connected as {obj.ToString()}");
    }

    private void AlpacaCryptoStreamingClient_OnWarning(string obj)
    {
        Console.WriteLine($"{environment}: Crypto Streaming Client warning {obj}");
    }

    private void AlpacaCryptoStreamingClient_OnError(Exception obj)
    {
        Console.WriteLine($"{environment}: Crypto Streaming Client error {obj.Message}");
    }

    private void AlpacaDataStreamingClient_SocketClosed()
    {
        Console.WriteLine($"{environment}: Data Streaming Client Socket Closed");
    }

    private void AlpacaDataStreamingClient_SocketOpened()
    {
        Console.WriteLine($"{environment}: Data Streaming Client Socket Opened");
    }

    private void AlpacaDataStreamingClient_Connected(AuthStatus obj)
    {
        Console.WriteLine($"{environment}: Data Streaming Client connected as {obj.ToString()}");
    }

    private void AlpacaDataStreamingClient_OnWarning(string obj)
    {
        Console.WriteLine($"{environment}: Data Streaming Client warning {obj}");
    }

    private void AlpacaDataStreamingClient_OnError(Exception obj)
    {
        Console.WriteLine($"{environment}: Data Streaming Client error {obj.Message}");
    }

    private void AlpacaStreamingClient_OnWarning(string obj)
    {
        Console.WriteLine($"{environment}: Streaming Client warning {obj}");
    }

    private void AlpacaStreamingClient_OnError(Exception obj)
    {
        Console.WriteLine($"{environment}: Streaming Client error {obj.Message}");
    }

    private void AlpacaStreamingClient_OnTradeUpdate(ITradeUpdate obj)
    {
        Console.WriteLine($"{environment}: Streaming Client on trade {obj.Order.Symbol}");
    }
}
```

**Comment by ooples** [comment] 2022-03-20 12:05
@OlegRa Can you assign this one to me so I can help him out?

**Comment by OlegRa** [comment] 2022-03-20 13:02
@ooples I've briefly checked the test and the most probable root cause of this problem is simple - there are no separate servers for the live and paper crypto streaming. In fact, there is only one streaming endpoint for both cases and data depends only on the key/secret pair (at least for stock streaming it's true).

**Comment by ooples** [comment] 2022-03-21 22:42
@OlegRa You can go ahead and close this issue. I helped him with the issue and your theory was correct

**Closed** 2022-03-21 22:52 UTC
Labels: bug
