### ISSUE TITLE
SocketException: The requested name is valid, but no data of the requested type was found

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#274] opened 2021-01-14 19:29 UTC
I'm getting this error message about once every 3 days running the API but not enough where I can confidently reproduce it. Is this a known issue and/or is there a fix for it?

**Comment by OlegRa** [comment] 2021-01-16 10:04
@ooples It's not an SDK-specific problem and even more it's not a .NET -specific problem. The root cause of this issue is in native Win SOCK implementation. 

Unfortunately, the currently used WebSocket client library [WebSocket4Net](https://github.com/kerryjiang/WebSocket4Net) doesn't handle this problem at all. You can try to report this problem in the related repo but I'm not sure it alive now - the last NuGet version is about 3 years old.

I have plans for replacing the WebSocket client library with a built-in implementation available in .NET out of the box. I hope this implementation deals with Win SOCK issues much better. But this refactoring work planned for upcoming months and most probably will be completed only in the scope of the next major release (5.0) this summer.

If you can handle this exception (even though the UnhandledExceptions handler) just re-create all WebSocket connections - it should help. I'll not close this issue but instead re-target it to the next major release.

**Comment by OlegRa** [comment] 2021-03-24 15:22
@ooples Will close it, for now, if you will see this error again in the versions later than 5.0.2-alpha1, please, re-open it.

**Closed by OlegRa** 2021-03-24 15:22 UTC
Labels: bug
