### ISSUE TITLE
[FEATURE]: Exception - Alpaca Error message details

### ISSUE THREAD

**Issue by walterX12** [alpacahq/alpaca-trade-api-csharp#609] opened 2023-04-02 09:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I wish if Alpaca exceptions caused by Bad Request 400, would include more detailed information about root cause.

### Describe the solution you'd like

If Alpaca server response is non-OK ( e.g. 400- bad request) with payload indicating detailed description, what exactly is wrong with the request, it would be very helpful if exception thrown would include Message with such description.

Currently exception is thrown:
 - `Alpaca.Markets.RestClientErrorException.Message` = `BadRequest`.
 - `Alpaca.Markets.RestClientErrorException.HttpStatusCode` = `400/BadRequest`.

The suggested solution would result in 
 - `Alpaca.Markets.RestClientErrorException.Message` = `{"message":"Invalid symbol(s): NONEXIST%2FUSDT does not match ^[A-Z]+/[A-Z]+$"}`, wchich is payload returned for example by `https://data.alpaca.markets/v1beta3/crypto/us/latest/bars?symbols=NONEXIST%252FUSDT`
 - `Alpaca.Markets.RestClientErrorException.HttpStatusCode` = `400/BadRequest`.

It would still enable users recognize specific Error codes. For example `403 Forbidden - Buying power or shares is not sufficient` . documented in 
https://alpaca.markets/docs/api-references/trading-api/orders/  would be easily recognized by code `HttpStatusCode`.

**Comment by OlegRa** [comment] 2023-04-02 14:18
@walterX12 This code already exists but unfortunately, it expects the `code` field. I'll change this behavior in the release of 6.2.0 next week.

**Comment by OlegRa** [comment] 2023-04-19 15:16
@walterX12 You can test changes in version 6.1.12 and the upcoming 6.0.2-beta2 as well. Please, check and close this issue if the problem is resolved.

**Comment by OlegRa** [comment] 2023-05-17 15:50
I will close it for now. @walterX12 if you are still experiencing the original problem, please, re-open this issue.

**Closed by OlegRa** 2023-05-17 15:50 UTC
Labels: enhancement
