### ISSUE TITLE
System.OutOfMemoryExceptions being thrown from Alpaca.Market.HttpClientExtensions.callAndDeserializeAsync

### ISSUE THREAD

**Issue by ayushguptacoder** [alpacahq/alpaca-trade-api-csharp#438] opened 2022-01-05 21:49 UTC
**Package : Alpaca.Markets 5.2.4**
This does not happen all the time, but it does happen often, like every 5-6th call.

Code called :
```cs
var orders = await alpacaTradingClient.ListOrdersAsync(
    new ListOrdersRequest() { OrderStatusFilter = OrderStatusFilter.Open });
```

Response:

```cs
Error: Exception of type 'System.OutOfMemoryException' was thrown. 
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(HttpResponseMessage responseMessage, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
```

Code Called:
```cs
var positions = await alpacaTradingClient.ListPositionsAsync();
```

Response:

```cs
Error: Exception of type 'System.OutOfMemoryException' was thrown. 
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(HttpResponseMessage responseMessage, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
```

**Comment by OlegRa** [comment] 2022-01-05 22:40
@ayushguptacoder Could you please provide more information about your environment?

- [ ] Which version of .NET SDK do you use?
- [ ] What is your target .NET version?
- [ ] What is your target OS version/bitness?
- [ ] What is your process bitness?
- [ ] How much RAM do you have on the target box?
- [ ] What is the typical memory usage of your app?

I've never experienced such a problem on 64-bit applications running on a system with enough RAM amount. In fact, these exceptions are thrown by .NET internal HTTP subsystem during the deflating incoming messages for future deserialization. But in any case, if you'll provide more information I try to solve it. Maybe enabling HTTP/2 with compression as the default transport option was not a good idea or at least it should be possible to use HTTP/1.1 without compression for some scenarious.

**Comment by OlegRa** [comment] 2022-01-26 15:42
@ayushguptacoder I'll close this issue in the upcoming days if you'll not provide me with more information about your environment. Unfortunately, I'm unable to reproduce this problem on my side and according to the call stacks, this problem is related to .NET BCL code not to this SDK code itself.

**Closed** 2022-01-31 07:59 UTC
Labels: bug
